### ISSUE TITLE
Please add the metric dunam to the area section

### ISSUE THREAD

**Issue by ahmadhadidi** [DrorHarari/keypirinha-cvt#10]
Hi Dror,

Where I'm from we use the [metric dunam](https://en.wikipedia.org/wiki/Dunam) as a unit to measure the area of land. It would be really great if we had that in the package.

Great work on this project. Cheers!

**Comment by DrorHarari** [comment]
Hi Admad, where I leave the Dunam is also used by according to Wikipedia, the Dunam has different meaning in different countries:
- North Cyprus: 1337.8 square meters
- Iraq: 2500 square meters
- Turkey, Servia, Bosnia Hercegovina, Lebanon, Jordan, Israel: 1000 squere meters

If to go by majority it would be 1000 square meters - is it for you too?

**Comment by ahmadhadidi** [comment]
For us it's 1000 square meters.
(Turkey, Servia, Bosnia Hercegovina, Lebanon, Jordan, Israel: 1000 squere meters)

**Comment by DrorHarari** [comment]
OK, added.

**Comment by ahmadhadidi** [comment]
Thank you very much!
