### ISSUE TITLE
Temperature Conversion

### ISSUE THREAD

**Issue by ChristopherMJ** [DrorHarari/keypirinha-cvt#2]
I can't seem to get the syntax right for Temperature Conversion. The syntax used for other conversions doesn't seem to work (21 C F). Can you please give an example?

**Comment by DrorHarari** [comment]
Thanks @ChristopherMJ - there is indeed something wrong with the temperature - likely due to the format simplification changes.

Will fix it later...

**Comment by DrorHarari** [comment]
Fixed. Had problem finding unit with non-lowercase. Package can be downloaded here and it can be update automatically with PackageControl. Till then, a simple workaround is to use uppercase C, K or F.
