### ISSUE TITLE
How to convert from “l/100km”?

### ISSUE THREAD

**Issue by GilDev** [DrorHarari/keypirinha-cvt#6]
Hi,
I think the “/” is messing with Cvt, it won’t detect when I write “l/100km) and I have no idea on how I can convert from this unit.
Any tips? Thanks!

**Comment by DrorHarari** [comment]
@GilDev - I have tried to write ```15l/100km``` and it produced the following expected result:

![image](https://user-images.githubusercontent.com/1831901/75522393-8e357280-5a12-11ea-888a-2f4cfbe51b62.png)

What do you get when you type the same? I will probably add an alias to l/100km - maybe lphkm...

**Comment by GilDev** [comment]
I don’t have my Windows setup for a few weeks now… But it wasn’t showing the cat plugin at all in the search results after the “/”.

**Comment by DrorHarari** [comment]
I have added aliases without / -- for example l/100km can also now be written as lphkm (Liter Per Hundred KiloMeter)

Will take a day or two to self update if using PackageControl

**Comment by GilDev** [comment]
Great, thanks!
85be4d21aed0ae5c32299deb99538d1d3a04a638
