### ISSUE TITLE
Non-alphanumeric characters don’t work as unit aliases

### ISSUE THREAD

**Issue by chris-morgan** [DrorHarari/keypirinha-cvt#7]
I want this:

```
[unit/distance/Inches]
aliases = ″

[unit/distance/Feet]
aliases = ′

[unit/temperature/Celcius]
aliases = °,°C

[unit/temperature/Fahrenheit]
aliases = °F
```

(With the help of my Compose key, thanks to WinCompose, I genuinely type all of these things quite casually. Well, as casually as I *ever* type anything in feet or inches. And admittedly I’d use half of those symbols more comfortably for angular measurements in degrees, minutes and seconds. But yeah, dropping the degrees symbol and writing “-40F” instead of “−40°F” is genuinely a nuisance for me! For that matter, I’d rather like `−` (MINUS SIGN) to work rather than just `-` (HYPHEN-MINUS). I’m weird like this.)

But this doesn’t work; from a quick glance, it looks like this’ll be due to the input parser regular expression only being interested in alphanumeric characters.

**Comment by DrorHarari** [comment]
@chris-morgan that's one of the nice things about open source - if you're weird like this, you can will it to change for you just like you want it to be. You won't have to repeat this effort as this is very stable and unlikely to change.

I do not find this addition compelling so I am closing this issue.
